project:
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

date: last-modified

format:
  html:
    embed-resources: true
    self-contained-math: true
    df-print: kable
    toc: true

execute: 
  warning: false
  message: false
